version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2017
configuration: Release
platform:
- x64
before_build:
- cmd: pushd . && cd FluentTerminal.Client && npm install && npm run-script build && popd && nuget restore FluentTerminal.sln
after_build:
- cmd: '7z a FluentTerminal-v%APPVEYOR_BUILD_VERSION%-%APPVEYOR_REPO_COMMIT%.zip FluentTerminal.App\AppPackages\*'
artifacts:
  - path: 'FluentTerminal-v%APPVEYOR_BUILD_VERSION%-${APPVEYOR_REPO_COMMIT}.zip'
    name: AppPackage
build_script:
  - msbuild /maxcpucount:%NUMBER_OF_PROCESSORS% /t:Build /p:Configuration=Release /p:AppxBundle=Always /p:Platform="x86|x64" /v:q /nologo FluentTerminal.sln
test_script:
  - echo Skipt tests run
deploy:
  release: 'FluentTerminal-%APPVEYOR_BUILD_VERSION%-${APPVEYOR_REPO_COMMIT}'
  description: 'Build ${APPVEYOR_REPO_COMMIT} for appveyor-ci-support branch'
  provider: GitHub
  auth_token:
    secure: rwuDF3ROrdEzxJ9HaT/aedOWRuiDPDp6T5a7WmdGBl54bm4d5z9S2L6SLMYD9WRo
  draft: false
  prerelease: false
  on:
    branch: appveyor-ci-support
    APPVEYOR_REPO_TAG: false
