version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2017
configuration: Release
platform:
- x86
assembly_info:
  patch: true
  file: 'FluentTerminal.App\Properties\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: pushd . && cd FluentTerminal.Client && npm install && npm run-script build && popd && nuget restore
after_build:
- cmd: '7z a FluentTerminal-v{version}-%APPVEYOR_REPO_COMMIT%.zip FluentTerminal.App\AppPackages\*'
artifacts:
  - path: 'FluentTerminal-v{version}-${APPVEYOR_REPO_COMMIT}.zip'
    name: AppPackage
build:
  project: FluentTerminal.sln
  parallel: true
  verbosity: minimal
test_script:
  - echo Skipt tests run
deploy:
  release: 'FluentTerminal-{version}-${APPVEYOR_REPO_COMMIT}'
  description: 'Build ${APPVEYOR_REPO_COMMIT} for appveyor-ci-support branch'
  provider: GitHub
  auth_token:
    secure: rwuDF3ROrdEzxJ9HaT/aedOWRuiDPDp6T5a7WmdGBl54bm4d5z9S2L6SLMYD9WRo
  draft: false
  prerelease: false
  on:
    branch: appveyor-ci-support
    APPVEYOR_REPO_TAG: false
